#!/system/bin/sh

#Create seperate primary boot cache partition using loop mount images for racks dualbootsd

#force mount /sdcard
MNTPARAM=dirsync,nosuid,nodev,noexec,relatime,uid=1000,gid=1015,fmask=0702,dmask=0702
    busybox mount vfat rw,$MNTPARAM /dev/block/mmcblk1p7 /sdcard

PRICACHE=/sdcard/pri-cache.img

    if ! [ -e $PRICACHE ] ; then
    	dd if=/dev/zero of=$PRICACHE bs=1024 count=1 seek=100000
    	mke2fs -F $PRICACHE
    fi

#create loop device node for cache
    mknod -m640 /dev/block/loop99 b 7 99

#setup loop mount for cache img from sdcard
    losetup /dev/block/loop99 $PRICACHE
    sleep 5

    busybox mount -t ext2 -o rw /dev/block/loop99 /cache
    chown /R system cache /cache
    chmod 0771 /cache
    chmod 0770 /cache/recovery

    busybox mount -o remount,rw /system
    chmod 0771 /cache/dalvik-cache
    busybox mount -o remount,ro /system
   